"""Shared helpers for contract tests.

The harness exposes three things:

* ``STEP7_FIXTURES`` — a dict keyed by Step-7 ``label`` that gives the
  recorded ``status``, ``shape``, ``count``, ``has_next`` for that probe.
  Use this to drive parametric tests so the recorded shape is the
  source of truth.

* ``make_paginated_response(shape, ...)`` — build a response body that
  matches the recorded pagination shape (``page_or_offset``, ``cursor``,
  or ``flat-dict``).

* ``assert_query_params(request, expected, allow_extra=...)`` — assert
  that the params on the wire are exactly the expected set. Defaults to
  strict (no extras allowed) so unknown / renamed kwargs surface
  immediately.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional
from urllib.parse import parse_qs

import httpx


# ---------------------------------------------------------------------------
# Step-7 fixture loading
# ---------------------------------------------------------------------------

# We deliberately do not vendor the Step-7 JSON into the test tree — the
# canonical copy lives in engineering-documents and is regenerated by the
# nightly probe job. We read it at import time when present, and fall back
# to an embedded subset for when the engineering-documents repo is not
# checked out alongside (e.g. CI clones jana-eko-client only).

_STEP7_PATH_ENV = "EKO_STEP7_FIXTURE_PATH"
_DEFAULT_STEP7_PATH = (
    Path(__file__).resolve().parents[3]
    / "engineering-documents"
    / "jana"
    / "docs"
    / "operations_docs"
    / "eko_client_audit_20260424_artifacts"
    / "eko_step7_probe_results_20260428.json"
)

# Embedded subset — used when the live JSON is not on disk. Keep in sync
# with the audit artifact when shapes change. Each entry is the minimal
# set of fields we currently assert on.
_EMBEDDED_STEP7: List[Dict[str, Any]] = [
    {"label": "ct-emissions",                       "status": 200, "shape": "cursor",         "count": None, "has_next": True},
    {"label": "ct-emissions-country_iso3-USA",      "status": 200, "shape": "cursor",         "count": None, "has_next": True},
    {"label": "ct-emissions-country_code-USA-BUGGY","status": 200, "shape": "cursor",         "count": None, "has_next": True},
    {"label": "ct-emissions-gas-co2",               "status": 200, "shape": "cursor",         "count": None, "has_next": True},
    {"label": "ct-emissions-gas_type-co2-BUGGY",    "status": 400, "shape": "flat-dict",      "count": None, "has_next": None},
    {"label": "ct-sectors",                         "status": 200, "shape": "page_or_offset", "count": 26,   "has_next": False},
    {"label": "ct-countries",                       "status": 200, "shape": "page_or_offset", "count": 251,  "has_next": True},
    {"label": "ct-assets",                          "status": 200, "shape": "cursor",         "count": None, "has_next": True},
]


def _load_step7() -> Dict[str, Dict[str, Any]]:
    """Load Step-7 probe results into a dict keyed by ``label``."""
    path_str = os.environ.get(_STEP7_PATH_ENV)
    path = Path(path_str) if path_str else _DEFAULT_STEP7_PATH
    if path.exists():
        with path.open() as f:
            data = json.load(f)
    else:
        data = _EMBEDDED_STEP7
    out: Dict[str, Dict[str, Any]] = {}
    for item in data:
        # Normalise the shape string — the live JSON sometimes appends
        # the discovered keys in parentheses (e.g.
        # ``flat-dict (['avg_value', ...])``); we only care about the
        # leading shape token.
        raw_shape = item.get("shape") or ""
        norm_shape = raw_shape.split(" ", 1)[0] if raw_shape else raw_shape
        out[item["label"]] = {
            "status": item["status"],
            "shape": norm_shape,
            "count": item.get("count"),
            "has_next": item.get("has_next"),
        }
    return out


STEP7_FIXTURES: Dict[str, Dict[str, Any]] = _load_step7()


# ---------------------------------------------------------------------------
# Response builders
# ---------------------------------------------------------------------------

def make_paginated_response(
    shape: str,
    *,
    results: Optional[List[Dict[str, Any]]] = None,
    count: Optional[int] = None,
    next_url: Optional[str] = None,
    flat_payload: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Build a response body matching one of the three Step-7 shapes.

    Args:
        shape: One of ``"page_or_offset"``, ``"cursor"``, ``"flat-dict"``.
        results: List of result dicts (used for paginated shapes).
        count: Total record count. Required for ``page_or_offset``;
            ``None`` for ``cursor``.
        next_url: ``next`` URL string or ``None``.
        flat_payload: Body dict for ``flat-dict`` shape (e.g. the
            ``totals`` endpoints).

    Returns:
        Dict suitable for use as the JSON body of a respx ``Response``.
    """
    if shape == "page_or_offset":
        return {
            "count": count if count is not None else len(results or []),
            "next": next_url,
            "previous": None,
            "results": results or [],
        }
    if shape == "cursor":
        return {
            "next": next_url,
            "previous": None,
            "results": results or [],
        }
    if shape == "flat-dict":
        return dict(flat_payload or {})
    raise ValueError(f"Unknown shape: {shape!r}")


# ---------------------------------------------------------------------------
# Query-param assertion
# ---------------------------------------------------------------------------

def _decode_params(request: httpx.Request) -> Dict[str, List[str]]:
    """Return the request's query string as ``{name: [values]}``."""
    qs = request.url.query.decode() if isinstance(request.url.query, bytes) else str(request.url.query)
    if not qs:
        return {}
    return parse_qs(qs, keep_blank_values=True)


def assert_query_params(
    request: httpx.Request,
    expected: Mapping[str, Any],
    *,
    allow_extra: Optional[Iterable[str]] = None,
) -> None:
    """Assert exact wire-level query params.

    Args:
        request: The captured ``httpx.Request`` (from respx route).
        expected: ``{name: value}`` mapping. ``value`` is compared
            stringified — multi-value params should pass a list of
            strings. ``None`` entries are not allowed (the client must
            drop ``None`` kwargs before they reach the wire).
        allow_extra: Iterable of param names that may legitimately be on
            the wire but are not under test (e.g. pagination
            ``page_size``). Defaults to ``("page_size", "limit")``.

    Raises:
        AssertionError: If a required param is missing, has the wrong
            value, or an unexpected (non-allowed) param appears.
    """
    if allow_extra is None:
        allow_extra = ("page_size", "limit")
    allow_extra_set = set(allow_extra)

    actual = _decode_params(request)

    # Check expected keys present and correct
    for name, value in expected.items():
        assert name in actual, (
            f"Expected query param {name!r} missing from request "
            f"(got params: {sorted(actual)})"
        )
        actual_values = actual[name]
        if isinstance(value, list):
            expected_values = [str(v) for v in value]
        else:
            expected_values = [str(value)]
        assert actual_values == expected_values, (
            f"Query param {name!r}: expected {expected_values!r}, "
            f"got {actual_values!r}"
        )

    # Check no unexpected extras (apart from the whitelist)
    unexpected = set(actual) - set(expected) - allow_extra_set
    assert not unexpected, (
        f"Unexpected query params on the wire: {sorted(unexpected)} "
        f"(expected only {sorted(expected)} plus whitelist {sorted(allow_extra_set)})"
    )
